const cards = [
	'https://www.trustedtarot.com/img/cards/the-fool.png',
	'https://www.trustedtarot.com/img/cards/the-magician.png',
	'https://www.trustedtarot.com/img/cards/the-high-priestess.png',
	'https://www.trustedtarot.com/img/cards/the-empress.png',
	'https://www.trustedtarot.com/img/cards/the-emperor.png',
	'https://www.trustedtarot.com/img/cards/the-heirophant.png',
	'https://www.trustedtarot.com/img/cards/the-chariot.png',
	'https://www.trustedtarot.com/img/cards/strength.png',
	'https://www.trustedtarot.com/img/cards/the-hermit.png',
	'https://www.trustedtarot.com/img/cards/wheel-of-fortune.png',
	'https://www.trustedtarot.com/img/cards/justice.png',
	'https://www.trustedtarot.com/img/cards/the-hanged-man.png',
	'https://www.trustedtarot.com/img/cards/death.png',
	'https://www.trustedtarot.com/img/cards/temperance.png',
	'https://www.trustedtarot.com/img/cards/the-tower.png',
	'https://www.trustedtarot.com/img/cards/the-moon.png',
];

//  -------- TESTING jQUERY --------
// if (typeof $ == 'undefined') {
// 	console.log('oops! I still have to link my jQuery properly!');
// } else {
// 	console.log('I did it! I linked jQuery and this js file properly!');
// }
// console.log('this is $', $);

const $cardPicker = $('<div>').addClass('cardPicker');
$('body').append($cardPicker);
$cardPicker.text('Add random image');
$cardPicker.css('cursor', 'pointer');

// let randomCard = [Math.floor(Math.random() * cards.length)];
// console.log(cards[randomCard])
/* <-- by addding cards(the array) in front of [randomCard](position/index #) we get the actual element at the index # generated by [randomCard] (math.floor(math.random)etc......)  I KNOW I WANT TO USE (cards[randomCard]) in the img.attr so that when I use it in a function it keeps generating a random url from the array (rather than hard code one url like we did in this afternoon's example) */

// let $newCardImage = $('<img>').addClass('newCardImage'); <-- needs to be inside the function so that we are actually creating a new/additional image every time the function is triggered, not just ont image the keeps changes/being replaced
// $newCardImage.attr('src', (cards[randomCard]));

const pickCard = () => {
	let randomCard = Math.floor(Math.random() * cards.length);
	let $newCardImage = $('<img>').addClass('newCardImage');
	$newCardImage.attr('src', cards[randomCard]);
	$('body').append($newCardImage);
};

$cardPicker.on('click', pickCard);

// --------- LECTURE PRACTICE ----------------------
// const $btn = $('#btn')
// console.log($btn)
// $btn.on('click', () => {
//     console.log("button was clicked!")
// });

// // $btn.on('click', () => {
// //     $('body').append("it seems as if it has been cliked")
// //     }
// // )

// const addText = () => {
//     $('body').append('it seems as if it has been cliked');
// }
// $btn.on('click', addText);

// const changeClass = () => {
//     $('body').toggleClass('black')
// }

// $('#btn').on('click', changeClass)
